#以下是测试和正式环境通用配置
server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /ifc
spring:
  mvc:
    static-path-pattern: /cn.com.bgy.ifc/static/**
  freemarker:
      request-context-attribute: request
      suffix: .html
      template-loader-path: classpath:/cn.com.bgy.ifc/templates/
  jmx:
      enabled: false
---
#正式环境配置
spring:
  datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        initialSize: 10
        max-active: 100
        max-idle: 200
        min-idle: 10
        validation-query: SELECT 1
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        max-wait: 60000
        jdbc-url: jdbc:mysql://47.99.100.79:3306/intelligent_fire_control?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=CTT&rewriteBatchedStatements=true
        username: root
        password: root



  secondary:
           max-idle: 10
           max-wait: 10000
           min-idle: 5
           initial-size: 5
           query: SELECT 1
           test-on-borrow: false
           test-while-idle: true
           time-between-eviction-runs-millis: 18800

  jackson:
        date-format: 'yyyy-MM-dd HH:mm:ss'
        time-zone: GMT+8


  jpa:
        show-sql: true
        hibernate:
        ddl-auto: update
  http:
        encoding:
        charset: utf-8
        enabled: true
primary:
   mapperLocations: classpath:mapper/**/*.xml
#配置分页插件pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql



